---
- name: devstack controller setup
  vars:
    tmpl_path: {{temlpate_path}}
  hosts: controllers
  remote_user: stack
  tasks:
  - git: repo=https://github.com/openstack-dev/devstack.git
         dest=/home/stack/devstack
  - template: src={{'{{tmpl_path}}'}} dest=/home/stack/devstack/local.conf
  - shell: /home/stack/devstack/stack.sh >> /home/stack/devstack.log

