---
- name: devstack compute setup
  hosts: computes
  remote_user: stack
  tasks:
  - git: repo=https://github.com/openstack-dev/devstack.git
         dest=/home/stack/devstack
  - template: src={{temlpate_path}} dest=/home/stack/devstack/local.conf
  - shell: /home/stack/devstack/stack.sh >> /home/stack/devstack.log
